#logging:
#  level.root: debug
## datasource configuration is required
spring.datasource:
  url: jdbc:mysql://localhost:3306/camunda?autoReconnect=true&sendFractionalSeconds=false
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456
# url: jdbc:h2:./camunda-h2-default/process-engine;TRACE_LEVEL_FILE=0;DB_CLOSE_ON_EXIT=FALSE
# driver-class-name: org.h2.Driver
# username: sa
# password: sa

spring:
  resources:
    static-locations: classpath:/static/,classpath:/public/
#  main:
#    web-application-type: reactive
#  web:
#    resources:
#      add-coors-header: true
#      chain:
#        strategy:
#          content:
#            cache: false
#            enabled: true
#            policy: "default-src 'self'; connect-src 'self' http://localhost:8081"
#server:
#  servlet:
#    session:
#      cookie:
#        secure: true


camunda:
  bpm:
    webapp:
      header-security:
        content-security-policy-disabled: true